server:
  port: 9090

geodb:
  scheme: https
  domain: wft-geo-db.p.rapidapi.com
  api-key: <API-KEY>
  version: v1

infotrecho:
  scheme: https
  domain: boaviagem-app.herokuapp.com
  context: api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect.storage_engine: innodb
        dialect: org.hibernate.dialect.MySQL57Dialect